# This configuration is for training a system that cen then work
# with R-CNN detection outputs.
TRAIN_ON_BOUNDING_BOXES: TRUE
NORMALIZE_BOUNDING_BOXES: TRUE

# Data point sampling parameters
THRESHOLD_NEGATIVE_DISTANCE: 200
FILTER_PAIRS: True  # Only consider pairs within THRESHOLD_NEGATIVE_DISTANCE

# Restriction to avoid imbalanced dataset of having 10 negatives for 1 positive example
MAX_NEGATIVE_EXAMPLES_PER_OBJECT: 10

# At validation time, we should test against the runtime
# situation, where we will classify every pair within
# THRESHOLD_NEGATIVE_DISTANCE
VALIDATION_MAX_NEGATIVE_EXAMPLES_PER_OBJECT: -1

# The size of the image patches that are output
PATCH_HEIGHT: 256
PATCH_WIDTH: 512

# The rescaling factor that is applied before the patch is extracted
# (In effect, setting this to 0.5 downscales by a factor of 2, so
#  the effective window w.r.t. the input image will be twice the specified
#  PATCH_HEIGHT, PATCH_WIDTH.)
IMAGE_ZOOM: 1.0

# Randomly moves the patch this many pixels away from the midpoint
# between the two sampled objects.
MAX_PATCH_DISPLACEMENT: 0


